function [transformed_PSF, transformed_PSF_frame, raw_PSF_frame] = transform_PSF(T_in_row_form, raw_PSF)
    % Generate a reference frame for the raw PSF, which is just the default
    % reference frame that imwarp() assumes if you don't pass one in.
    raw_PSF_frame = ...
        imref3d(size(raw_PSF), ...
                0.5+[0 size(raw_PSF,2)], ...
                0.5+[0 size(raw_PSF,1)], ...
                0.5+[0 size(raw_PSF,3)]) ;

    % Do the transform in the default way        
    [transformed_PSF, transformed_PSF_frame] = ...
        imwarp(raw_PSF, raw_PSF_frame, affine3d(T_in_row_form), 'Interp', 'cubic') ;
end
